### ISSUE TITLE
Enhance documentation in README

### ISSUE THREAD

**Issue by alwell-kevin** [patalwell/fullStackGo#1]
It would be great to know how to run this app, including dependencies from instructions described in the README...

Keep up the great work! 

![giphy](https://user-images.githubusercontent.com/26548363/62573924-314f5080-b865-11e9-80a1-7c666f5263b2.gif)

@patalwell

**Comment by patalwell** [comment]
Hey Kevin,

There is a note in the README.md in regards to a lack of runtime instructions. 

Note: This repository is currently a work in progress and will reflect the latter after due time.

I can update the README.md later on tonight if you'd like to pull the project locally and give it a whirl.

Do you have go installed?

**Comment by patalwell** [comment]
Updated Readme.md with runtime instructions. Please see the official go docs for directions on installing go for your OS. If you're using a mac you can simply use `brew install go`. What's more, make sure you have the appropriate directory structure set up in order to properly pull packages.
